run:
  timeout: 10m
linters:
  enable:
    - ineffassign
    - revive
    - gosec
    - govet
    - misspell
    - staticcheck
    - wastedassign
linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
